# Create geojson file for neighbourhoods
shapefile for wards in `gis.city_ward`  
the ward table is pulled from gccview  

for neighbourhoods `gis.neighbourhood`  

To create geojson in pgAdmin:

```
CREATE TABLE cnangini.wards_geojson AS
SELECT ST_AsGeoJSON(ST_ASTEXT(geom)) FROM gis.city_ward;
```

```
CREATE TABLE cnangini.neighbourhoods_geojson AS
SELECT ST_AsGeoJSON(ST_ASTEXT(geom)) FROM gis.neighbourhood;
```

In [1]:
import sys
sys.executable

'/home/test/anaconda3/envs/vfh/bin/python'

In [2]:
%matplotlib inline
import numpy as np
import pandas as pd
import pandas.io.sql as pandasql
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.ticker as ticker

from IPython.display import HTML, display
import datetime
import matplotlib.dates as mdates
import os

from datetime import datetime

import json

# Variables

In [25]:
ward=10

In [26]:
fname = '../../../Documents/PROJECTS/VFH/COT_PAGE/INTERIM_DATA/FROM_PGADMIN/tripdata_092018.csv'
df = pd.read_csv(fname)

In [27]:
print(df.shape)

(4478890, 17)


In [28]:
list(df)

['pickup_datetime',
 'dow',
 'hh',
 'dropoff_datetime',
 'pickup_ward2018',
 'dropoff_ward2018',
 'pickup_gc_intersection_id',
 'dropoff_gc_intersection_id',
 'pickup_neighbourhood',
 'dropoff_neighbourhood',
 'timewindow',
 'pickup_geom',
 'dropoff_geom',
 'lat_pickup',
 'lon_pickup',
 'lat_dropoff',
 'lon_dropoff']

In [29]:
print(len(df['pickup_neighbourhood'].sort_values().unique()))
df['pickup_neighbourhood'].sort_values().unique()

141


array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140.,  nan])

In [30]:
df.loc[df['pickup_ward2018']==ward, 'pickup_neighbourhood'].sort_values().unique()

array([70., 76., 77., 78., 81., 82., 84., 85.])

In [31]:
df.loc[df['dropoff_ward2018']==ward, 'dropoff_neighbourhood'].sort_values().unique()

array([70., 76., 77., 78., 81., 82., 84., 85.])